### ISSUE TITLE
Invalid naming

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/quiz_maker#12]
https://github.com/asharif123/quiz_maker/blob/69cbcee1fc86a177f7c0a486773e2b849f95697c/UIMethods.cs#L29
https://github.com/asharif123/quiz_maker/blob/69cbcee1fc86a177f7c0a486773e2b849f95697c/UIMethods.cs#L63
https://github.com/asharif123/quiz_maker/blob/69cbcee1fc86a177f7c0a486773e2b849f95697c/UIMethods.cs#L81
https://github.com/asharif123/quiz_maker/blob/69cbcee1fc86a177f7c0a486773e2b849f95697c/UIMethods.cs#L159
...
When I mentioned that your method naming should be consistent I did not mean that every method should start with the same name,
but instead all methods that achieve similar things should.

When the method is supposed to print stuff to the console, starting with "Print..." is ok 👍 
But for methods that receive a value from user input, this does not indicate that the method is returning a value to the program

**Comment by asharif123** [comment]
fixed issue #12 by fixing inconsistent naming
