### ISSUE TITLE
Method should be in logic

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/quiz_maker#13]
https://github.com/asharif123/quiz_maker/blob/69cbcee1fc86a177f7c0a486773e2b849f95697c/UIMethods.cs#L151-L156
Methods that dont interact with the user should be located in your logic class.

If you want to print what the program is doing in such methods you should not use `Console.WriteLine()` but either separate into two methods (one for ui and one for logic) 
or you should use the debug from Diagnostics: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.writeline?view=net-8.0
This way the output is not meant for the user, but only for internal tracking what your code do

**Comment by asharif123** [comment]
fixed issue #13 by moving method into logic file
