### ISSUE TITLE
kind of a strange name for this method

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#16]
https://github.com/asharif123/quiz_maker/blob/f2f9ea317fad8b1e1d4bb1ec69101860d467cdd4/UIMethods.cs#L64

Method is named PrintInputAnswers which is kind of a strange name. First of all this method does 2 different things which should be avoided. Each method should do only one thing at a time.

You can create a new method called PrintAnswerInputMessage and add the Console.WriteLine($"\nPlease input your answers, you can enter upto {MAX_ANSWERS} answers!\n"); in it and you can also create a new one to get the input for the answers.

**Comment by asharif123** [comment]
fixed issue #16 by fixing strange naming of a method
