### ISSUE TITLE
The message from this method is printed 4 times

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#17]
https://github.com/asharif123/quiz_maker/blob/f2f9ea317fad8b1e1d4bb1ec69101860d467cdd4/UIMethods.cs#L96

The resolution of this issue should take place after issue #16. 

There's no point into printing "Please input your answers, you can enter upto 4 answers!" for each answer. This message should be printed once, outside the loop and of course before the loop starts.

**Comment by asharif123** [comment]
fixed issue #17 by getting rid of code asking user to enter answers 4 times
