### ISSUE TITLE
How about creating a method for getting and validatting the indexOfAssignedCorrectAnswer

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#18]
https://github.com/asharif123/quiz_maker/blob/f2f9ea317fad8b1e1d4bb1ec69101860d467cdd4/UIMethods.cs#L118-L138

You can create a new method that will get the input and validate it in order to be in spec. After validating this method can return back the indexOfAssignedCorrectAnswer in order to be used by the CreateListOfQuizCards.

**Comment by asharif123** [comment]
fixed issue #18 by creating a method to get the index of the correct answer
