### ISSUE TITLE
What if the file does not exist?

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#19]
https://github.com/asharif123/quiz_maker/blob/b7eef7cd0d5942c8185daa2d882a306995a9fb29/Logic.cs#L37

Since you selected to not have a specific mode for Loading a quiz the user can hit by mistake a button and go into Load mode. There's a chance that there's no file already saved. This will lead to an unexpected shutdown of the program with a FileNotFoundException. 

This case should be handled!

**Comment by asharif123** [comment]
fixed issue #19 by adding check statement to determine if there are available quizzes to play with
