### ISSUE TITLE
More methods can be extracted to minimize complexity

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#21]
https://github.com/asharif123/quiz_maker/blob/b7eef7cd0d5942c8185daa2d882a306995a9fb29/UIMethods.cs#L179-L223

There are some options to extract some methods out of this bigger one to minimize complexity. 

For example, you can create a method to check if the index is valid since there's a check for this 
indexGuessOfUser < Constants.MIN_ANSWERS || indexGuessOfUser > Constants.MAX_ANSWERS -> This can be in a Logical method that will take the indexGuessOfUser as an input, and return back if the index is valid or not.

Another option is to create a UI method for displaying the question and the available answers.

There are also more options for UI methods

**Comment by asharif123** [comment]
fixed issue #21 by reducing method complexity
