### ISSUE TITLE
else case is redundant

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#23]
https://github.com/asharif123/quiz_maker/blob/b7eef7cd0d5942c8185daa2d882a306995a9fb29/Logic.cs#L64-L67

Since you have a return true if the userGuess equals quiz.correctAnswer there's no point for an else. you can return false immediately after the if

but you can also return immediately the result of userGuess == quiz.correctAnswer which is the neater option

**Comment by asharif123** [comment]
fixed issue #23 by getting rid of redundant else statement
