### ISSUE TITLE
Name needs some adjustment

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#25]
https://github.com/asharif123/quiz_maker/blob/3a20a6fe8ffa26675a34aec4e24831a5c48e733a/UIMethods.cs#L31

The name of the method is good but it doesn't provide the full detail on what this method does. The method is not converting an integer, it's more of a validation method, since it gets the input, it converts it and if the integer is not valid it also provides some messages. 

Also, string userInput = UIMethods.GetUserInput(); -> no need to invoke the method by providing the class name since this method is a UIMethod itself.

**Comment by asharif123** [comment]
fixed issue #25 by updating method name to ValidateUserInputIsInteger
