### ISSUE TITLE
Naming needs work

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#26]
https://github.com/asharif123/quiz_maker/blob/3a20a6fe8ffa26675a34aec4e24831a5c48e733a/UIMethods.cs#L278

Method is well structured and written okay at this point but it's name needs some more work. First of all it's not consistent with the other names. Secondly the name should provide a description of the method's action and not user's action. 

For example, the name of the method AskUserToPlayAgain is doing exaclty that, it provides information on what the method will do.

So take some time and rethink this particular name

**Comment by asharif123** [comment]
fixed issue #26 by updating method name to "GenerateRandomQuizCard"
