### ISSUE TITLE
This is never used

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#27]
https://github.com/asharif123/quiz_maker/blob/3a20a6fe8ffa26675a34aec4e24831a5c48e733a/Logic.cs#L55

Reading from a file/database is an expensive operation in programming so it should be done in a wise way. In this particular situation, you are using an expensive operation and you also never use the result. This means that this invocation is a waste of resources. 

Please remove it.

**Comment by asharif123** [comment]
fixed issue #27 by getting rid of listOfQuizCards as it is never used
