### ISSUE TITLE
This method should be splitted

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#28]
https://github.com/asharif123/quiz_maker/blob/3a20a6fe8ffa26675a34aec4e24831a5c48e733a/UIMethods.cs#L225-L231

This method does more than 1 thing, it prints the contents of a quiz and it also gets the user answer. Based on that it's name is wrong. But it's better if you split this method into 2, meaning that PrintContentsOfLoadedQuiz will be invoked into UserPlaysRandomQuizCard first and then GetUserAnswer will be invoked after that to continue with the flow.

**Comment by asharif123** [comment]
fixed is
