### ISSUE TITLE
Why are you rechecking the answer?

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#29]
https://github.com/asharif123/quiz_maker/blob/3a20a6fe8ffa26675a34aec4e24831a5c48e733a/Logic.cs#L79

On UIMethods you have already verified if the user has answered correclty on in a wrong way. You can provide answerIfCorrect to this method instead of providing the guessOfUser and the selectedQuizCard again. 

Same as you do on PrintResultInformation method on UIMethods

**Comment by asharif123** [comment]
fixed issue #29 by invoking Logic.checkIfAnswerIsCorrect method in UIMethods.cs file
