### ISSUE TITLE
no need to have constants for 0

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/quiz_maker#30]
or even put better, you don't need a constant for a value that never changes (checking if a list is empty will almost ever be a check against 0) if it is clearly visible to a reader
https://github.com/asharif123/quiz_maker/blob/e831cfa8f7ac03b31d0fa84e99abff72cf3605da/Constants.cs#L20

**Comment by asharif123** [comment]
fixed issue #30 by getting rid of constant assignment to 0
