### ISSUE TITLE
static keyword

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/quiz_maker#31]
I noticed some comments in your code:
https://github.com/asharif123/quiz_maker/blob/e831cfa8f7ac03b31d0fa84e99abff72cf3605da/Logic.cs#L7
https://github.com/asharif123/quiz_maker/blob/e831cfa8f7ac03b31d0fa84e99abff72cf3605da/Logic.cs#L10

especially the part "needs to be static" which let me see that you don't understand this keyword yet.
So you could take a quick look again at this video if you haven't already
https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560456

But to provide you with a short summary: those properties/fields does not *need to be* static 👆 but you *can* make them static if this makes sense to your program.
You probably thought those values need to be static because of a compiler error where the origin is that if you call a static method you can only use static variables (which totally makes sense if you think about it: if you call a method of a class that has no instance you cannot access the field of an instance 🤷)
So of course you could make your logic class non-static and then have non-static methods and variables,
but then if you want to use it you would need to create an instance like `var gameLogic = new Logic();`

**Comment by asharif123** [comment]
fixed issue #31 by defining static keyword usage
