### ISSUE TITLE
Do you really need this function?

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/quiz_maker#32]
https://github.com/asharif123/quiz_maker/blob/e831cfa8f7ac03b31d0fa84e99abff72cf3605da/UIMethods.cs#L20-L24
It basically does nothing more than just Console.ReadLine(); and return this value,
so that you effectively have a function that only calls another function.

**Comment by asharif123** [comment]
fixed issue #32 by getting rid of unnecessary method
