### ISSUE TITLE
The random object should be handled as constant.

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#7]
https://github.com/asharif123/quiz_maker/blob/328e36b33bfd10f7b535c7c3f7412ab38952f2d5/UIMethods.cs#L91

Instead of creating a new object each time this method is invoked you can use the one that you have defined on your program.cs and pass it as a parameter.

**Comment by asharif123** [comment]
fixed issue #7 by passing random as an argument in UIMethods
