### ISSUE TITLE
A new list of answers should be defined for each question

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#8]
https://github.com/asharif123/quiz_maker/blob/328e36b33bfd10f7b535c7c3f7412ab38952f2d5/UIMethods.cs#L63

By initializing your list of answers outside the loop that handles the questions, you will end up with a list of answers that will contain at least 4*maxQuestions. This is because you are keep adding answers to that least without emptying it after each question.

We suggest to initialize it inside the loop and use it the way you do now.

**Comment by asharif123** [comment]
fixed issue #8 by defining a new answers list for each question
