### ISSUE TITLE
Naming is a little off

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/quiz_maker#9]
https://github.com/asharif123/quiz_maker/blob/328e36b33bfd10f7b535c7c3f7412ab38952f2d5/UIMethods.cs#L71

change the name from InputQuestions to at least InputQuestion as your code reads only one question. Also you don't need to invoke it by the class as it's already in UIMethods.cs class

UIMethods.InputQuestions(); -> InputQuestions();

**Comment by asharif123** [comment]
fixed issue #9 by fixing naming is off issue
